config/routes.rb
Frc2012::Application.routes.draw do
  devise_for :admins do
    get '/login'  => 'devise/sessions#new',     as: 'new_user_session'
    get '/logout' => 'devise/sessions#destroy', as: 'destroy_user_session'
  end

  namespace :admin do
    resources :posts
    root to: 'posts#index'
  end
  
  match 'login', to: 'admins#sign_in'

  match 'sponsors',    to: 'home#sponsors'
  match 'mentors',     to: 'home#mentors'
  match 'team',        to: 'home#team'
  match 'aboutsite',   to: 'home#aboutsite'
  match 'mechanical',  to: 'home#mechanical'
  match 'electrical',  to: 'home#electrical'
  match 'programming', to: 'home#programming'
  match 'marketing',   to: 'home#marketing'
  match 'webdesign',   to: 'home#webdesign'
  match 'robot',       to: 'home#robot'
  
  root to: 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin

  # converts line breaks '\n' with '<br/>'
  def body_html
    body.gsub(/\n/, '<br/>').html_safe
  end

end

app/controllers/admin/administration_controller.rb
class Admin::AdministrationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_admin!
  layout 'admin'

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdministrationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new params[:post]
    if @post.save
      redirect_to admin_post_path(@post)
    end
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes params[:post]
      redirect_to admin_post_path(@post)
    end
  end
  
  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery
  layout 'main'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @posts = Post.order 'created_at desc'
    render 'home/index'
  end

  def sponsors
    render 'home/sponsors'
  end

  def mentors
    render 'home/mentors'
  end

  def team
    render 'home/team'
  end
  
  def aboutsite
    render 'home/aboutsite'
  end

  def mechanical
    render 'home/mechanical'
  end
  
  def electrical
    render 'home/electrical'
  end
  
  def marketing
    render 'home/marketing'
  end
  
  def programming
    render 'home/programming'
  end
  
  def webdesign
    render 'home/webdesign'
  end

  def robot
    render 'home/robot'
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_form.html.haml
= f.hidden_field( :admin_id, value: current_admin.id )
.group
  = f.label :title, t("activerecord.attributes.post.title", :default => "Title"), :class => :label
  = f.text_field :title, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :body, t("activerecord.attributes.post.body", :default => "Body"), :class => :label
  = f.text_area :body, :class => 'text_area'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), admin_posts_path, :class => "text_button_padding link_button"

app/views/admin/posts/_sidebar.html.haml
.block.notice
  %h3 News Manager
  .content
    %p Hello
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Future Tools Go Here

app/views/admin/posts/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_post_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Post
    .inner
      = form_for @post, :url => admin_post_path(@post), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/posts/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Posts
    .inner
      %table.table
        %tr
          %th.first Author
          %th Title
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @posts.each do |post|
          %tr{:class => cycle("odd", "even")}
            %td
              = post.admin.email
            %td
              = link_to post.title, admin_post_path(post)
            %td
              = post.created_at.strftime "%b. #{post.created_at.day.ordinalize}, %Y at %l:%M %P"
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", admin_post_path(post)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_post_path(post)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_post_path(post), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/posts/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Post
    .inner
      = form_for :post, :url => admin_posts_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/posts/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_post_path
  .content
    .inner
      %p
        %b Author:
        = @post.admin.email
      %p
        %b Title:
        = @post.title
      %p= @post.body
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_post_path(@post), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_post_path(@post), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/home/_post.html.haml
.post
  %h3.title
    = post.title
    -# %span.time= post.created_at.strftime '%l:%M %P'
    %span= link_to image_tag('icon-gear.png'), admin_post_path(post)
    %span.date= post.created_at.strftime "%b. #{post.created_at.day.ordinalize}, %Y" 
  %p.body= post.body_html

app/views/home/aboutsite.html.haml
#mentors
  %p.description Our website uses the Ruby on Rails framework in order to operate. This framework is used by very popular companies like NASA, Cisco, amazon.com, IBM, Oracle, Yahoo!, Siemens, EA Games, BBC, and C|Net. The files that make up the site are coded in HAML and SASS, so that code writing is as efficient as possible. HAML and SASS are basically equivalent to HTML and CSS, and they both come out in the end as HTML and CSS to the browser. The difference is that it is much more efficient in coding. Large amounts of dynamic content can be added very easily, and it's simple to add a new page without having to re-write the entire layout over again. Another advantage is that HAML does not use ending tags. Instead, it relies on white space and tabs. Ruby on Rails is a Model View Controller (MVC) type of framework. It was first described in 1979 by Trygve Reenskaug who worked at Xerox. In a very basic description, the model is an object that represents data, the view is the visualization of the model, and the controller can change the state of the model.
  %p Here we have two images. One is the sponsors page in HTML, and one is written in HAML.
  = image_tag 'haml.jpg', width: '50%', align: 'left'
  = image_tag 'html.jpg', width: '50%', align: 'right'
  <br>
  %p For more information about how Ruby on Rails works, please visit their website.

app/views/home/electrical.html.haml
#subteams
  %h1.subteam Electrical
  %div.teamlead
    %p.teamlead Team Lead: Juan Laza
    %div.centeredImage
      = image_tag 'juanweb.png'
  %h2.subteam Members:
  <br>
  %div.member
    %h3 Anthony Baksh
    %p Senior
  %div.member
    %h3 Sydney Dawes
    %p Freshman
  %div.member
    %h3 Juan Laza
    %p Senior
  %div.member
    %h3 Corey Mapes
    %p Sophomore
  %div.member
    %h3 Richard Scott
    %p Senior
  %div.member
    %h3 Tamara Sorto
    %p Senior

app/views/home/index.html.haml
#introduction
  = image_tag 'DSC_8265.png'
  = image_tag 'firstandrr.png'
  %p
  %p Welcome to the Mekheads Team 1604 official website. We are a robotics team based in the Central Florida area, and take part in competitions held by #{link_to 'FIRST', 'http://usfirst.org'}, a non-profit organization. Harmony High School, TECO/Paths, St. Cloud High School, and Gateway High School are all involved with our group. The mission of Mekheads 1604 is to promote science, technology, engineering, and math (STEM). We accomplish all of these at every meeting. There are also subteams within the main team, that each have their own "team lead". These include mechanical, electrical, programming, web design, and marketing. For more information about each section, visit #{link_to 'this', '/team'}page. We meet every Thursday from 6-8 in Mr. Berkley's room at TECO. If you are interested in joining our team, please contact Mrs. Berkley at berkleyj(at)osceola.k12.fl.us.
  %p
    %strong This year's game, Rebound Rumble, is here!
    #{link_to 'Click here', 'http://youtu.be/hK_kzwlki2M'} to see a video of the game.

#news
  = render partial: 'post', collection: @posts

app/views/home/marketing.html.haml
#subteams
  %h1.subteam Marketing
  %div.teamlead
    %p.teamlead Team Lead: Emma Sandell
  %h2.subteam Members:
  <br>
  %div.member
    %h3 Jessica Dendulk
    %p Senior
  %div.member
    %h3 Katelyn Enger
    %p Senior
  %div.member
    %h3 Sarah Gonzalez
    %p Junior
  %div.member
    %h3 Corey Mapes
    %p Senior
  %div.member
    %h3 Sarah Partridge
    %p Senior
  %div.member
    %h3 Ruchi Patel
    %p Senior
  %div.member
    %h3 Schvanie Rambarran
    %p Senior
  %div.member
    %h3 Emma Sandell
    %p Senior
  %div.member
    %h3 Dustin Townsend
    %p Junior
  %div.member
    %h3 Aleisha Wilson
    %p Senior

app/views/home/mechanical.html.haml
#subteams
  %h1.subteam Mechanical
  %div.teamlead
    %p.teamlead Team Lead: Cody Mannifield
    %div.centeredImage
      = image_tag 'codyweb.png'
  %h2.subteam Members:
  <br>
  %div.member
    %h3 Stan Aviles
    %p Freshman
  %div.member
    %h3 Kaylin Clark
    %p Sophomore
  %div.member
    %h3 Sheyra Concepcion
    %p Junior
  %div.member
    %h3 Justin Farley
    %p Junior
  %div.member
    %h3 Peter Fiji
    %p Senior
  %div.member
    %h3 Bradley Hernandez
    %p Sophomore
  %div.member
    %h3 Tyler Hughes
    %p Junior
  %div.member
    %h3 Cody Mannifield
    %p Senior
  %div.member
    %h3 Robert Mannifield
    %p Freshman
  %div.member
    %h3 Mackenzie Mcglone
    %p Senior
  %div.member
    %h3 George Neher
    %p Sophomore
  %div.member
    %h3 Tesi Washington
    %p Freshman

app/views/home/mentors.html.haml
#mentors
  %p.description These are all the wonderful mentors that help us achieve our goals. They are responsible for the success and knowledge in our team, and we are glad we have so many.
  %div.mentor
    %h2 Gavin Barnes
    = image_tag 'gavin.png', class: 'mentor'
    %p Gavin Barnes has been a mentor to the Mekheads since 2008.  During that time, his efforts were chiefly dedicated to the instruction of labview as the programming mentor until this most recent year, where the programing crew opted for their first foray into the land of C++.  Outside of FIRST, he is employed as a Systems Engineer at Lockheed Martin.  He has both a Bachelor&#39;s and Master&#39;s Degree in Mechanical Engineering from the University of Central Florida where he is now pursuing an Masters in Business Administration as well.  Apparently, he felt the need to dedicate an entire decade of his life to one educational institution.
  %div.mentor
    %h2 Matt Bartoe
    = image_tag 'matt.png', class: 'mentor'
    %p Matthew Bartoe is a Mechanical Mentor on his second year with team 1604.  He is persuing his Masters in Mechanical Enginering at the University of Central Florida (UCF).  While at UCF he has been working at Lockheed Martin for the past five and a half years in the College Work Experience Program (CWEP).  According to Tim Lanning (Mekheads President), he was raised by wolves in the Siberian tundra.  After his graduation in May 2012, he plans to work in an engineering field with a focus in robotics. 
  %div.mentor
    %h2 Ricardo Arencibia
    %p Ricardo Arencibia likes long walks on the beach, rescuing innocent animals, and reading by the fireplace (because Florida is very cold especially during snowboarding season). He joined the Mekheads to help teach kids how to create one of the meanest, baddest, and coolest robots for the FIRST competition. Outside of FIRST, he is employed full time at Lockheed Martin as an Electrical Engineer. Rick graduated from the University of Florida with a Bachelor&#39;s degree in Electrical Engineering and is pursuing a Master&#39;s degree in Electrical Engineering from the Georgia Institute of Technology, specializing in control systems and digital signal processing. Teaching motto&#58; &quot;Build a man a fire, and he&#39;ll be warm for a day. Set a man on fire, and he&#39;ll be warm for the rest of his life&quot; - Terry Pratchett
  %div.mentor
    %h2 Ethan Pemble
    = image_tag 'ethan.png', class: 'mentor'
    %p Ethan works as a software developer for Cloudspace.  He graduated in 2010 from University of Central Florida with a degree in Computer Engineering.  He dreams of some day building 'the coolest treehouse ever.'  
  %div.mentor
    %h2 Cliff Berkley
    = image_tag 'mrberkley.png', class: 'mentor'
    %p Mr. Berkley provides the knowledge base for the drive-train on our robot.  He is the automotive technology instructor at TECO.  He began his career with automobiles right out of high school, enlisting with the army and eventually attaining the rank of Warrant Officer in automotive maintance.  He served two tours in Vietnam, was stationed in Germany, and finished his service in Okalahoma.  After his discharge, he went on to work at several dealerships as the shop foreman before deciding to open his own successful auto repair garage.  He dabbled in racing, owning several cars of his own as well as being chief mechanic for a very successful Pikes Peak hill-climb car.  Mr. Berkley enjoys working on anything, as long as it has wheels and an engine!
  %div.mentor
    %h2 Jane Berkley
    = image_tag 'mrsberkley.png', class: 'mentor'
    %p Mrs. Berkley brings together all of the resources that the Mekheads require in order to have a successful FIRST Robotics team.  She is currently teaching Honors Biology and Advanced Placement Biology at the high school, but has taught band, choir, and math during her career.  She has taught every grade level from 2nd through 12th grade.  A National Board Certified teacher, she is the Department Chair at Harmony High School.  She and Mr. Berkley have two daughters, one a mechanical engineer with Lockheed Martin and the other a high-school American History teacher.  Mrs. Berkley has held down a wide variety of jobs in the past:  optometrists&#39; assistant, pharmacy technician, title clerk, office manager, Challenge By Choice Ropes Instructor, white-water raft guide down the Arkansas River, swim coach, and city pool manager (just to name a few).  Her hobbies have ranged from gardening to race-car driver.  As long as students have the excitement and drive to want to learn, she is ready to facilitate the learning!
  %div.mentor
    %h2 Adrian Goetz
    %p Adrian was born in Colorado and then moved to Miami in high school. He got a degree in film from UCF and has been working as a photographer at Disney for the past five years. On the side, he photographs events such as weddings, and does portrait sessions. He lived with three engineers in college and it fostered a love for science and technology that has only grown since.
  %div.mentor
    %h2 Evan Herndon
    %p Evan is the smartest mentor we have on the Mekheads team. Not only is he intelligent, but he is also incredibly good-looking. He&#39;s a transplant from the cornfields of southwestern Indiana, coming from a small town with the motto &#34;You&#39;ll Like Linton.&#34; Evan has many different hobbies including cars, dirt bikes, snowboarding (which he gets to do often in Florida), music, and of course robotics. Evan graduated from Purdue University in May 2011 with a bachelor&#39;s degree in Mechanical Engineering and is now working online towards his master&#39;s degree in Mechanical Engineering from the Georgia Institute of Technology, specializing in control systems and robotics. Evan works full time at Lockheed Martin as a Mechanical Engineering Leadership Development Program Associate. He wasn&#39;t raised by wolves, but rumor has it that he moonlights as the popular British race car driver, The Stig.
  %div.mentor
    %h2 Nancy Lanning
    = image_tag 'nancylanning.png', class: 'mentor'
    %p Nancy has worked the past 15 years for Oracle Corporation.  Her current role is a Senior Software Support Manager for the Applications Integrations Architecture team.  Previously, she has worked at Harris Corporation, USF&amp;G Insurance Company and B. Green and Company in a Programmer/analyst role.  She has an undergrad degree in Business Administration with her major being in Information Systems.   She currently resides in St. Cloud with her husband and 3 sons.
  %div.mentor
    %h2 Kevin Thomas
    = image_tag 'kevin.png', class: 'mentor'
    %p Kevin Thomas teaches Physics, Chemistry, and Physical Science at PATHS. He became involved with the Mekheads in Fall 2011. Mr. Thomas works on helping the Mekheads understand physical concepts that help them decided how to build and program the robot. He got his Bachelor&#39;s degree in Physics and Master&#39;s degree in Science Education from UCF. His goal is to reinforce science principles and encourage all the Mekheads to pursue science and engineering in their careers.
  %div.mentor
    %h2 Eric Bourgeois
    %p I&#39;m from a small town in Louisiana called Vacherie.  I attended college at Louisiana State University where I earned a Bachelor&#39;s of Science in Mechanical Engineering.  I moved to Florida in June 2009 to start working as a Mechanical Engineer for Lockheed Martin. My current title is Stress Analyst, but I also work in structure dynamics from time to time supporting various different programs.  I became an engineer because of an interest in cars.  I actually have a 1967 Firebird back in Louisiana.  In my spare time, I write computer codes in Matlab to help me design new suspension components for it.  I also enjoy trail riding on my 4-wheeler.  I plan to start work on a master&#39;s degree in Mechanical Engineering in either the summer or fall of this year.
  %div.mentor
    %h2 Joanne Sirois
    %p 

app/views/home/programming.html.haml
#subteams
  %h1.subteam Programming
  %div.teamlead
    %p.teamlead Team Lead: Walter Hernandez
    %div.centeredImage
      = image_tag 'walterweb.png'
  %h2.subteam Members:
  <br>
  %div.member
    %h3 Alexander Alvarez
    %p Sophomore
  %div.member
    %h3 Tiffany Anglero
    %p Senior
  %div.member
    %h3 Chris Feauto
    %p Junior
  %div.member
    %h3 James Gallon
    %p Sophomore
  %div.member
    %h3 Andrew Geltz
    %p Junior
  %div.member
    %h3 German Gamboa
    %p Junior
  %div.member
    %h3 Devin Gorley
    %p Sophomore
  %div.member
    %h3 Walter Hernandez
    %p Senior
  %div.member
    %h3 Abdulslam Khan
    %p Freshman
  %div.member
    %h3 Mike Lopez
    %p Junior

app/views/home/robot.html.haml
%p Robot Page Coming Soon

app/views/home/sponsors.html.haml
#sponsors
  %p.description Mekheads Team 1604 are grateful to these sponsors for the continuation of our team. Without you, our team would not be possible.
  %div.sponsor
    %h2= link_to 'Walt Disney World Resort Company', 'http://www.disney.com/'
    = image_tag 'disneytransparent.png', class: 'sponsor'
    %p Walt Disney has supported our team since the beginning, and we are very grateful for their support. Thank you Disney!
  %div.sponsor
    %h2= link_to 'Lockheed Martin', 'http://www.lockheedmartin.com/'
    = image_tag 'lockheed-martintransparent.png', class: 'sponsor'
    %p Lockheed Martin has been a long-time sponsor of our team, and we are very glad to have them. Thank you Lockheed Martin!
  %div.sponsor
    %h2= link_to 'NASA', 'http://www.nasa.gov/'
    = image_tag 'nasatransparent.png', class: 'sponsor'
    %p NASA (National Aeronautics and Space Administration) is a new sponsor for our 2012 season, and we appreciate their support. Thank you NASA!
  %div.sponsor
    %h2= link_to 'AmeraTrail', 'http://www.ameratrail.com/'
    = image_tag 'ameratrailtransparent.png', class: 'sponsor'
    %p AmeraTrail has been painting our robot teal for a few years now, and their work is greatly appreciated. Thank you AmeraTrail!
  %div.sponsor
    %h2= link_to 'Walmart', 'http://www.walmart.com/'
    = image_tag 'walmarttransparent.png', class: 'sponsor'
    %p Walmart is a returning sponsor for our 2012 season, and we are glad they can help us out. Thank you Walmart!
  %div.sponsor
    %h2= link_to 'Progress Energy', 'http://www.progress-energy.com/'
    = image_tag 'progressenergytransparent.png', class: 'sponsor'
    %p Progress Energy has helped our team in the past, and they are a valued sponsor of our team. Thank you Progress Energy!
  %div.sponsor
    %h2= link_to 'Mullinax Ford', 'http://www.mullinaxford.com/'
    = image_tag 'MullinaxLogotransparent.png', class: 'sponsor'
    %p Mullinax Ford is a brand new sponsor to our team. Thank you Mullinax Ford!
  %div.sponsor
    %h2= link_to 'Cloudspace', 'http://www.cloudspace.com/'
    = image_tag 'cloudspace-originalcolor.png', class: 'sponsor'
    %p Cloudspace is another new sponsor this year.  Thank you!


app/views/home/team.html.haml
#team
  = image_tag 'banner.png'
  %p.description Our team is organized into five different subteams. This type of organization allows for substantial productivity, and helps everything run smoothly. These teams also work together to make sure everything works well with what the other subteams are doing. Towards the end of the build season, all the subteams come together to construct a fantastic robot.
  %p.description These are the subteams for the 2012 build season. Information about each subteam can be found by clicking on the name.
  %div.subteam
    %h2 #{link_to 'Mechanical', '/mechanical'}
    %p We are responsible for the building of the robot, and anything to do with the hardware on it.
  %div.subteam
    %h2 #{link_to 'Electrical', '/electrical'}
    %p We make sure all of the elctronic components of the robot are working together and work with the mechanical pieces of the robot.
  %div.subteam
    %h2 #{link_to 'Programming', '/programming'}
    %p We give the robot a brain, and make all the elctronics work together and perform a task.
  %div.subteam
    %h2 #{link_to 'Marketing', '/marketing'}
    %p Reaches out and communicates to the community by creating brochures, presentations, videos, signs, and buttons promoting the team and soliciting sponsorship.
  %div.subteam
    %h2 #{link_to 'Web Design', '/webdesign'}
    %p We are responsible for the website of the team.

app/views/home/webdesign.html.haml
#team
  %h2 Web Design
  %p.description Team Lead: Tyler Coleman

app/views/layouts/_banner.html.haml
.box
  #logo= link_to image_tag('newwebsiteheader.jpg'), root_path

app/views/layouts/_footer.html.haml
.box
  %p &#169; 2012 Mekheads 1604
  <br>
  %p 
    <a href="http://www.CynthiaSays.com/org/cynthiatested.htm"><img src="http://www.CynthiaSays.com/images/Ctested.gif" alt="Cynthia Tested!" height="31" width="88"></a>
    = link_to image_tag( 'html5.png'), 'http://validator.w3.org/check?uri=http%3A%2F%2Fmekheads.org%2F'

app/views/layouts/_links.html.haml
.box
  #bar
    %ol
      %li= link_to 'The Team', team_path, class: ('active' if current_page?(action: 'team'))
      %li= link_to 'Our History', root_path, class: ('active' if current_page?(action: 'history'))
      %li= link_to 'Our Mentors', mentors_path, class: ('active' if current_page?(action: 'mentors'))
      %li= link_to 'Our Sponsors', sponsors_path, class: ('active' if current_page?(action: 'sponsors'))
      %li= link_to 'About This Site', aboutsite_path, class: ('active' if current_page?(action: 'aboutsite'))

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title mekheads.org
    = stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/default/style'
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} mekheads.org
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              %a.logout{:href => "/logout"}= t("web-app-theme.logout", :default => "Logout")
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} mekheads.org.
        #sidebar
          = yield :sidebar

app/views/layouts/main.html.haml
!!!
%html
  %head
    %title Mekheads 1604
    = favicon_link_tag '/assets/favicon.jpg'
    = stylesheet_link_tag :main
    = javascript_include_tag :application

  %body
    #banner
      = render partial: '/layouts/banner'
    
    #links
      = render partial: '/layouts/links'

    #content
      .box= yield

    #footer
      = render partial: '/layouts/footer'